resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/68648612f916e8adaf6c9ca5fe39bc6712470a6a/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test
  - validate-mainnet

extra-deps:
  - libsystemd-journal-1.4.4

  # Currently Hackage only
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 68648612f916e8adaf6c9ca5fe39bc6712470a6a
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 2d0e0747f1c17bedfc251406ca9b1a59501071b1
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 423a7359049b0fd6fb2a931c50877cae2a96eaae
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Not yet in Stack
  - bimap-0.4.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: f6fcda280ddd1d4ef87e5203d65d132f924a6e39

  - time-units-1.0.0

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 0ebeacf643153a88fe0c23527449ca21b985d7d4
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
