resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/398e5279e36c92df5ca30f1e68a9482d139686f4/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- shelley/chain-and-ledger/executable-spec/test
- byron/chain/executable-spec
- byron/ledger/executable-spec
- semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

ghc-options:
  "$everything": -Wall -fwarn-redundant-constraints

allow-newer: true

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.2 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- Unique-0.4.7.6
- bimap-0.4.0
- monad-stm-0.1.0.2

- git: https://github.com/input-output-hk/cardano-prelude
  commit: 398e5279e36c92df5ca30f1e68a9482d139686f4

- git: https://github.com/input-output-hk/cardano-base
  commit: 6e28d0913ff0f27ac64a6fa517250362897b0869
  subdirs:
    - binary
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
- moo-1.2
- gray-code-0.3.1

nix:
  shell-file: nix/stack-shell.nix
