resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cca3c4f8da1de19321e96a5a7cca376bc6c37637/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test
  - validate-mainnet


extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: cca3c4f8da1de19321e96a5a7cca376bc6c37637
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: b676160954cea07d4378ccca870a61242bc188a2
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: ad86dcb64e8a5f3bd7670655ab92b50921946479
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Currently Hackage only
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: de45bf135fc0c575753613ee157378a28f9261e2

  - time-units-1.0.0

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: f1c4ceef7d7ea6fb4425484c2b19b84048a3549d
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
