resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/56fadcea03417771f4b3666fd1dfc9bad8df1484/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 56fadcea03417771f4b3666fd1dfc9bad8df1484
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0e26a4f00324100b4c34f2a9c7606ae03e94d7a2
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 5fabb962689edd2cc0c6d0a0e382419a496d57fc
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 545448938bf620bb2a25212e1686916cfa3acee9
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e22be186e0b1018260ed7c5166871f82a869b94d
    subdirs:
      - contra-tracer

  # Not yet in Stack
  - bimap-0.4.0

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - Unique-0.4.7.6

nix:
  shell-file: nix/stack-shell.nix
