resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fda38e60007a019c0c8569e8a0fc08f2102c92cc/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - libsystemd-journal-1.4.4

  # Currently Hackage only
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fda38e60007a019c0c8569e8a0fc08f2102c92cc
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 14f9b09920813447a4060b6810bf17fc4ea35840
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 423a7359049b0fd6fb2a931c50877cae2a96eaae
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Not yet in Stack
  - bimap-0.4.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 92e6b42167d1399971df788b691423222722c2f6

  - time-units-1.0.0

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 3ac2191fc4c68b46b7f6c08e2873f71949cc68e7
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
