resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/dc40b2e60cee4e808ffaa275926ade74a6c987d1/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: dc40b2e60cee4e808ffaa275926ade74a6c987d1
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 5c575d46afbfe333de0ccba70b084db8302abf42
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 11b674a10e76ab266a37225d82955fd8b1f80e27
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: bea0e079fc32ed316ce352d17d14199a680e3f6c
    subdirs:
      - contra-tracer

  # Not yet in Stack
  - bimap-0.4.0

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - Unique-0.4.7.6

nix:
  shell-file: nix/stack-shell.nix
