resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/bd7eb69d27bfaee46d435bc1d2720520b1446426/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- shelley/chain-and-ledger/executable-spec/test
- byron/chain/executable-spec
- byron/ledger/executable-spec
- semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

ghc-options:
  "$everything": -Wall -fwarn-redundant-constraints

allow-newer: true

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.2 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- Unique-0.4.7.6
- bimap-0.4.0
- monad-stm-0.1.0.2

- git: https://github.com/input-output-hk/cardano-prelude
  commit: bd7eb69d27bfaee46d435bc1d2720520b1446426

- git: https://github.com/input-output-hk/cardano-base
  commit: c845509c307af9df956ef203ac8ad67fe4d5d065
  subdirs:
    - binary
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
- moo-1.2
- gray-code-0.3.1

nix:
  shell-file: nix/stack-shell.nix
