resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - tasty-hedgehog-1.0.0.2

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-base
    commit: 2f0d4cc5b4798901333e199aa44e3a041a7aaaf1
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 9f96b7462a41d449826a4cc5f93dad395354cfe6
    subdirs:
      - semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: d998ff661aebae783a68725f3834af472bfa6468
    subdirs:
      - contra-tracer

  # Not yet in Stack
  - bimap-0.4.0
  - Unique-0.4.7.6
  - quiet-0.2

nix:
  shell-file: nix/stack-shell.nix
