env:
  BUILD_DIR: "/build/cardano-ledger"
  STACK_ROOT: "/build/cardano-ledger.stack"
  CACHE_DIR: "/cache/cardano-ledger"

steps:
  - label: 'nightly tests'
    command:
      - ".buildkite/nightly-tests.sh"
    agents:
      system: x86_64-linux
