env:
  BUILD_DIR: "/build/cardano-ledger-specs"
  STACK_ROOT: "/build/cardano-ledger-specs.stack"
  CACHE_DIR: "/cache/cardano-ledger-specs"

steps:
  - label: 'nightly tests'
    command:
      - ".buildkite/nightly-tests.sh"
    agents:
      system: x86_64-linux
