# The Buildkite pipeline definition.
# See https://buildkite.com/docs/pipelines for documentation.

steps:
  - label: 'check-cabal-project'
    command: "nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh"
    agents:
      system: x86_64-linux

  - label: 'stack-cabal-sync'
    command: 'nix-shell ./nix -A iohkNix.stack-cabal-sync-shell --run .buildkite/stack-cabal-sync.sh'
    agents:
      system: x86_64-linux

  - label: 'ormolisation'
    command: 'scripts/ormolise.sh'
    agents:
      system: x86_64-linux
