name:                utxo
version:             0.1.0.0
github:              "input-output-hk/shelley-ledger-rules"
author:              "IOHK Formal Metheds Team"
maintainer:          "formal.methods@iohk.io"

extra-source-files:
- README.md

description:         UTxO Executable Model

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - cryptonite
  - memory

tests:
  utxo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - utxo
    - hspec
